// Mocks generated by Mockito 5.0.16 from annotations
// in music_app_clean_architecture/test/features/album/presentation/bloc/album_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:music_app_clean_architecture/core/error/failures.dart' as _i5;
import 'package:music_app_clean_architecture/features/album_search/domain/entities/album.dart'
    as _i6;
import 'package:music_app_clean_architecture/features/album_search/domain/usecases/get_album.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [GetAlbumUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAlbumUseCase extends _i1.Mock implements _i3.GetAlbumUseCase {
  MockGetAlbumUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Album>> call(_i3.Params? params) =>
      (super.noSuchMethod(Invocation.method(#call, [params]),
              returnValue: Future<_i2.Either<_i5.Failure, _i6.Album>>.value(
                  _FakeEither_0<_i5.Failure, _i6.Album>()))
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Album>>);
  @override
  String toString() => super.toString();
}
